### ISSUE TITLE
Error parsing from indexer API doesn't work properly

### ISSUE THREAD

**Issue by banool** [aptos-labs/aptos-ts-sdk#176]
When you get an error from the indexer API it looks like this:
```
/Users/dport/a/aptos-api-key-examples/indexer-api/typescript/node_modules/.pnpm/@aptos-labs+ts-sdk@0.0.4/node_modules/@aptos-labs/ts-sdk/src/client/core.ts:100
  if ("message" in response.data && "error_code" in response.data) {
      ^
TypeError: Cannot use 'in' operator to search for 'message' in
    at aptosRequest (/Users/dport/a/aptos-api-key-examples/indexer-api/typescript/node_modules/.pnpm/@aptos-labs+ts-sdk@0.0.4/node_modules/@aptos-labs/ts-sdk/src/client/core.ts:100:7)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async queryIndexer (/Users/dport/a/aptos-api-key-examples/indexer-api/typescript/node_modules/.pnpm/@aptos-labs+ts-sdk@0.0.4/node_modules/@aptos-labs/ts-sdk/src/internal/general.ts:131:20)
    at async getNumberOfDelegatorsForAllPools (/Users/dport/a/aptos-api-key-examples/indexer-api/typescript/node_modules/.pnpm/@aptos-labs+ts-sdk@0.0.4/node_modules/@aptos-labs/ts-sdk/src/internal/staking.ts:46:44)
    at async Object.main [as handler] (/Users/dport/a/aptos-api-key-examples/indexer-api/typescript/src/main.ts:11:20)
    at async Object.run (/Users/dport/a/aptos-api-key-examples/indexer-api/typescript/node_modules/.pnpm/cmd-ts@0.13.0/node_modules/cmd-ts/src/command.ts:186:24)
    at async runSafely (/Users/dport/a/aptos-api-key-examples/indexer-api/typescript/node_modules/.pnpm/cmd-ts@0.13.0/node_modules/cmd-ts/src/runner.ts:46:20)
    at async run (/Users/dport/a/aptos-api-key-examples/indexer-api/typescript/node_modules/.pnpm/cmd-ts@0.13.0/node_modules/cmd-ts/src/runner.ts:27:18)
 ELIFECYCLE  Command failed with exit code 1.
```

The code that causes this issue: https://github.com/aptos-labs/aptos-api-key-examples/blob/640c186ec01932723d121a3e24fb41292c9002e4/indexer-api/typescript/src/main.ts.

Invoked like this:
```
pnpm main --indexer-api-url https://api.mainnet.aptoslabs.com/v1/graphql --api-key <key from developer portal>
```

More context here: https://aptos-org.slack.com/archives/C05NLAKJM9U/p1699362068290449.

**Comment by 0xmaayan** [comment]
I believe that should fix the problem https://github.com/aptos-labs/aptos-ts-sdk/pull/177/files#diff-201796f0b322359bbd1fe430bd72b900d0a14524f66c68f458746b072e5e8b62R38

**Comment by gregnazario** [comment]
@banool is this still an issue?

**Comment by gregnazario** [comment]
This should be fixed.
