### ISSUE TITLE
[Bug] run ts-example failed

### ISSUE THREAD

**Issue by linsheng9731** [aptos-labs/aptos-ts-sdk#228]
# 🐛 Bug Description

run example failed.
when run command  `pnpm run transfer_coin` , it throws error.

## How to reproduce
run command
```
pnpm run transfer_coin
```

**Stack trace / error message**
```
ts-test@1.0.0 transfer_coin /Users/admin/go/src/github.com/aptos-ts-sdk/examples/typescript
ts-node transfer_coin.ts

/Users/admin/go/src/github.com/aptos-ts-sdk/examples/typescript/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js:139
for (let i = startIndex ?? 0; i < array.length; i++) {
^

SyntaxError: Unexpected token '?'
at wrapSafe (internal/modules/cjs/loader.js:915:16)
at Module.compile (internal/modules/cjs/loader.js:963:27)
at Object.Module.extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module.load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at attemptRequireWithV8CompileCache (/Users/admin/go/src/github.com/aptos-ts-sdk/examples/typescript/node_modules/.pnpm/ts-node@10.9.1@[types+node@20.8.9_typescript](mailto:types+node@20.8.9_typescript)@5.2.2/node_modules/ts-node/dist/util.js:104:16)
at loadCompiler (/Users/admin/go/src/github.com/aptos-ts-sdk/examples/typescript/node_modules/.pnpm/ts-node@10.9.1@[types+node@20.8.9_typescript](mailto:types+node@20.8.9_typescript)@5.2.2/node_modules/ts-node/dist/configuration.js:237:56)
at resolveAndLoadCompiler (/Users/admin/go/src/github.com/aptos-ts-sdk/examples/typescript/node_modules/.pnpm/ts-node@10.9.1@[types+node@20.8.9_typescript](mailto:types+node@20.8.9_typescript)@5.2.2/node_modules/ts-node/dist/configuration.js:226:16)
ELIFECYCLE  Command failed with exit code 1.
```

## System information

env infomations:
```
node -v
v12.20.1

 pnpm -v
8.12.0
```

**Comment by 0xmaayan** [comment]
Hi @linsheng9731 could you share what sdk version you use? and what network you run the test against? 

Running on latest sdk version `1.0.0` and against devnet seems to work fine
