### ISSUE TITLE
ERR_HTTP2_ERROR: h2 is not supported

### ISSUE THREAD

**Issue by 0xfave** [aptos-labs/aptos-ts-sdk#540]
# 🐛 Bug Description

## How to reproduce

**Code snippet to reproduce**
```typescript
export async function swapAssets (
  aptos: Aptos,
  swapAddress: AccountAddress,
  senderAddress: Account,
  fromToken: AccountAddress,
  toToken: AccountAddress,
  amountIn: number,
  amountOutMin: number,
  recipient: AccountAddress,
)  {
  console.log("Swap Assets");
  const rawTxn = await aptos.transaction.build.simple({
    sender: senderAddress.accountAddress.toString(),
    data: {
      function: `${swapAddress.toString()}::router::swap_entry`,
      functionArguments: [amountIn, amountOutMin, fromToken, toToken, false, recipient],
    },
  });
  console.log("Swap txn: ", rawTxn);
  const pendingTxn = await aptos.signAndSubmitTransaction({ signer: senderAddress, transaction: rawTxn });
  const response = await aptos.waitForTransaction({ transactionHash: pendingTxn.hash });
  console.log("Swap succeed. - ", response.hash);
  return response.hash;
};
```
`"@aptos-labs/ts-sdk": "^1.29.1",`
**Stack trace / error message**
```
Swap Assets
346 |                                           ...options
347 |                                   });
348 |                                   session[kCurrentStreamsCount] = 0;
349 |                                   session[kGracefullyClosing] = false;
350 | 
351 |                                   const isFree = () => session[kCurrentStreamsCount] < session.remoteSettings.maxConcurrentStreams;
                                                                        ^
TypeError: null is not an object (evaluating 'session.remoteSettings.maxConcurrentStreams')
      at isFree (/home/fave/work/dev/bot/aptos-ts/node_modules/@aptos-labs/aptos-client/node_modules/got/node_modules/http2-wrapper/source/agent.js:351:67)
      at /home/fave/work/dev/bot/aptos-ts/node_modules/@aptos-labs/aptos-client/node_modules/got/node_modules/http2-wrapper/source/agent.js:449:12
      at emit (node:events:180:48)
      at #onConnect (node:http2:718:13)
      at onConnect (node:http2:855:23)
      at emit (node:events:180:48)
      at handshake (node:net:115:14)
Swap error: 965 |             var _a;
966 |             // Force clean-up, because some packages (e.g. nock) don't do this.
967 |             request.destroy();
968 |             // Node.js <= 12.18.2 mistakenly emits the response `end` first.
969 |             (_a = request.res) === null || _a === void 0 ? void 0 : _a.removeAllListeners('end');
970 |             error = error instanceof timed_out_1.TimeoutError ? new TimeoutError(error, this.timings, this) : new RequestError(error.message, error, this);
                                                                                                                    ^
RequestError: ERR_HTTP2_ERROR: h2 is not supported
 code: "ERR_HTTP2_ERROR"

      at /home/fave/work/dev/bot/aptos-ts/node_modules/@aptos-labs/aptos-client/node_modules/got/dist/source/core/index.js:970:111
      at native:1:1
      at native:1:1
      at /home/fave/work/dev/bot/aptos-ts/node_modules/@aptos-labs/aptos-client/node_modules/got/node_modules/@szmarczak/http-timer/dist/source/index.js:46:17
      at /home/fave/work/dev/bot/aptos-ts/node_modules/@aptos-labs/aptos-client/node_modules/got/node_modules/http2-wrapper/source/client-request.js:363:10
      at processTicksAndRejections (native:1:1)
      at #onConnect (node:http2:718:13)
      at onConnect (node:http2:855:23)
      at emit (node:events:180:48)
      at handshake (node:net:115:14)


Bun v1.1.24 (Linux x64)
```

## Expected Behavior

Make a swap

## System information

**System details:**
- Typescript SDK Version - 1.29.1
- Platform (e.g. Node, browser, etc.) node.js

**Comment by 0xfave** [comment]
the issue is related to bun 
use other package manager that supports http2
