### ISSUE TITLE
[Bug]  Error Using ts-sdk for Network Requests in Deno and Bun

### ISSUE THREAD

**Issue by WGB5445** [aptos-labs/aptos-ts-sdk#592]
# 🐛 Bug Description

 When using Deno and Bun, the error occurs because the client library depends on "got" and uses HTTP2 for requests.

You can reproduce the issue with these two repos.

```
error: Uncaught (in promise) RequestError
    at ClientRequest.<anonymous> (file:///Users/logan/Library/Caches/deno/npm/registry.npmjs.org/got/11.8.6/dist/source/core/index.js:970:111)
    at Object.onceWrapper (ext:deno_node/_events.mjs:518:26)
    at ClientRequest.emit (ext:deno_node/_events.mjs:405:35)
    at ClientRequest.origin.emit (file:///Users/logan/Library/Caches/deno/npm/registry.npmjs.org/@szmarczak/http-timer/4.0.6/dist/source/index.js:43:20)
    at ClientRequest.flushHeaders (file:///Users/logan/Library/Caches/deno/npm/registry.npmjs.org/http2-wrapper/1.0.3/source/client-request.js:363:10)
    at Object.runMicrotasks (ext:core/01_core.js:683:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:59:10)
    at runNextTicks (ext:deno_node/_next_tick.ts:76:3)
    at eventLoopTick (ext:core/01_core.js:182:21)
```
or 

```
346 |                                           ...options
347 |                                   });
348 |                                   session[kCurrentStreamsCount] = 0;
349 |                                   session[kGracefullyClosing] = false;
350 | 
351 |                                   const isFree = () => session[kCurrentStreamsCount] < session.remoteSettings.maxConcurrentStreams;
                                                                        ^
TypeError: null is not an object (evaluating 'session.remoteSettings.maxConcurrentStreams')
      at isFree (/Users/logan/code/temp/test_aptos_error/bun_test/node_modules/http2-wrapper/source/agent.js:351:67)
      at /Users/logan/code/temp/test_aptos_error/bun_test/node_modules/http2-wrapper/source/agent.js:449:12
      at emit (node:events:183:48)
      at #onConnect (node:http2:730:13)
      at onConnect (node:http2:867:23)
      at emit (node:events:183:48)
      at handshake (node:net:159:14)
965 |             var _a;
966 |             // Force clean-up, because some packages (e.g. nock) don't do this.
967 |             request.destroy();
968 |             // Node.js <= 12.18.2 mistakenly emits the response `end` first.
969 |             (_a = request.res) === null || _a === void 0 ? void 0 : _a.removeAllListeners('end');
970 |             error = error instanceof timed_out_1.TimeoutError ? new TimeoutError(error, this.timings, this) : new RequestError(error.message, error, this);
                                                                                                                    ^
RequestError: ERR_HTTP2_ERROR: h2 is not supported
 code: "ERR_HTTP2_ERROR"

      at /Users/logan/code/temp/test_aptos_error/bun_test/node_modules/got/dist/source/core/index.js:970:111
      at onceWrapper (native:1:1)
      at emitError (native:1:1)
      at /Users/logan/code/temp/test_aptos_error/bun_test/node_modules/http2-wrapper/source/client-request.js:363:10
      at processTicksAndRejections (native:1:1)
      at #onConnect (node:http2:730:13)
      at onConnect (node:http2:867:23)
      at emit (node:events:183:48)
      at handshake (node:net:159:14)

Bun v1.1.30 (macOS arm64)
```

## How to reproduce

https://github.com/WGB5445/test_deno_aptos_ts_sdk

https://github.com/WGB5445/test_bun_aptos_ts_sdk
 
## System information

**System details:**
- Typescript SDK Version: latest
- Platform: deno / bun

**Comment by leeduckgo** [comment]
For Deno, I think it's the problem of got verison `11.8.6`.

https://github.com/sindresorhus/got/issues/2387

> Not reproducible on deno@2.0.4 and got@14.4.3, maybe related to https://github.com/denoland/deno/pull/26264. Please update on your side.

It maybe will be solved after update the got version

**Comment by evan-gray** [comment]
Just ran into this using Bun and was able to successfully use the browser client in Bun by adding a `bun`-specific export [[doc](https://bun.sh/docs/runtime/modules#importing-packages)]. Tested using [bun patch](https://bun.sh/docs/install/patch). 🙌 


```diff
diff --git a/package.json b/package.json
index 55b6ec94f10f111f548ac061301dae755c2b1bda..e74371538ced50743641da2c9aed745bc87ab3ec 100644
--- a/package.json
+++ b/package.json
@@ -7,6 +7,11 @@
     "node": ">=15.10.0"
   },
   "exports": {
+    "bun": {
+      "require": "./dist/browser/index.browser.js",
+      "types": "./dist/browser/index.browser.d.ts",
+      "import": "./dist/browser/index.browser.mjs"
+    },
     "browser": {
       "require": "./dist/browser/index.browser.js",
       "types": "./dist/browser/index.browser.d.ts",
```

Perhaps this could be adopted in the package until Bun is fully [compatible with node:http2](https://bun.sh/docs/runtime/nodejs-apis#node-http2)?
